const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    UPDATE_STATUS_SUCCESS: 'UPDATE_STATUS_SUCCESS',
    UPDATE_STATUS_FAIL: 'UPDATE_STATUS_FAIL',

    //specialty
    GET_DATA_SPECIALTY_SUCCESS: 'GET_DATA_SPECIALTY_SUCCESS',
    GET_DATA_SPECIALTY_FAIL: 'GET_DATA_SPECIALTY_FAIL',

    //CLINIC
    GET_DATA_CLINIC_SUCCESS: 'GET_DATA_CLINIC_SUCCESS',
    GET_DATA_CLINIC_FAIL: 'GET_DATA_CLINIC_FAIL',

    // ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    // ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //admin
    GET_GENDER_START: 'GET_GENDER_START',
    GET_GENDER_SUCCESS: 'GET_GENDER_SUCCESS',
    GET_GENDER_FAIL: 'GET_GENDER_FAIL',
    GET_POSITION_START: 'GET_POSITION_START',
    GET_POSITION_SUCCESS: 'GET_POSITION_SUCCESS',
    GET_POSITION_FAIL: 'GET_POSITION_FAIL',
    GET_ROLE_START: 'GET_ROLE_START',
    GET_ROLE_SUCCESS: 'GET_ROLE_SUCCESS',
    GET_ROLE_FAIL: 'GET_ROLE_FAIL',
    CREATE_NEW_USER_START: 'CREATE_NEW_USER_START',
    CREATE_NEW_USER_SUCCESS: 'CREATE_NEW_USER_SUCCESS',
    CREATE_NEW_USER_FAIL: 'CREATE_NEW_USER_FAIL',
    READ_ALL_USER_START: 'READ_ALL_USER_START',
    READ_ALL_USER_SUCCESS: 'READ_ALL_USER_SUCCESS',
    READ_ALL_USER_FAIL: 'READ_ALL_USER_FAIL',
    DELETE_USER_START: 'DELETE_USER_START',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAIL: 'DELETE_USER_FAIL',
    EDIT_USER_FAIL: 'EDIT_USER_FAIL',

    READ_DOCTOR_SUCCESS: 'READ_DOCTOR_SUCCESS',
    READ_DOCTOR_FAIL: 'READ_DOCTOR_FAIL',

    CREATE_INFOR_DOCTOR_SUCCESS: 'CREATE_INFOR_DOCTOR_SUCCESS',
    CREATE_INFOR_DOCTOR_FAIL: 'CREATE_INFOR_DOCTOR_FAIL',

    //doctor
    GET_DETAILS_DOCTOR_SUCCESS: 'GET_DETAILS_DOCTOR_SUCCESS',
    GET_DETAILS_DOCTOR_FAIL: 'GET_DETAILS_DOCTOR_FAIL',

    GET_DOCTOR_SUCCESS: 'GET_DOCTOR_SUCCESS',
    GET_DOCTOR_FAIL: 'GET_DOCTOR_FAIL',

    UPDATE_DOCTOR_SUCCESS: 'UPDATE_DOCTOR_SUCCESS',
    UPDATE_DOCTOR_FAIL: 'UPDATE_DOCTOR_FAIL',

    GET_TIME_WORK_DOCTOR_SUCCESS: 'GET_TIME_WORK_DOCTOR_SUCCESS',
    GET_TIME_WORK_DOCTOR_FAIL: 'GET_TIME_WORK_DOCTOR_FAIL',

    GET_SCHEDULE_DOCTOR_SUCCESS: 'GET_SCHEDULE_DOCTOR_SUCCESS',
    GET_SCHEDULE_DOCTOR_FAIL: 'GET_SCHEDULE_DOCTOR_FAIL',

    GET_PRICE_SUCCESS: 'GET_PRICE_SUCCESS',
    GET_PRICE_FAIL: 'GET_PRICE_FAIL',

    GET_PROVINCE_SUCCESS: 'GET_PROVINCE_SUCCESS',
    GET_PROVINCE_FAIL: 'GET_PR_PAYMENT_FAIL',

    GET_PAYMENT_SUCCESS: 'GET_PAYMENT_SUCCESS',
    GET_PAYMENT_FAIL: 'GET_PAYMENT_FAIL',


    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    CHANGELANGUAGE: "CHANGELANGUAGE",
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL'
})

export default actionTypes;